######################################################################
# Automatically generated by qmake (3.0) Thu Dec 29 02:16:43 2016
######################################################################

QT += widgets network
CONFIG += c++14
TEMPLATE = app
TARGET = Birdview
INCLUDEPATH += .
QMAKE_CXXFLAGS += -Wfatal-errors

# Input
HEADERS += src/Birdview.hpp
SOURCES += src/Birdview.cpp \
           src/main.cpp
